import { WCOrder } from "@/types/woocommerce";

export const MOCK_ORDERS: readonly WCOrder[] = [
  {
    id: 1004,
    number: "1004",
    status: "processing",
    currency: "USD",
    currency_symbol: "$",
    date_created: "2026-06-29T10:30:00Z",
    date_created_gmt: "2026-06-29T10:30:00Z",
    discount_total: "15.00",
    shipping_total: "12.50",
    total: "284.50",
    total_tax: "21.00",
    customer_id: 42,
    customer_note: "Please leave package by the front door if no answer.",
    payment_method: "stripe",
    payment_method_title: "Credit Card via Stripe",
    transaction_id: "ch_3N8B7Z2eZvKYlo2C1g9JkL4M",
    store_id: "store-dribbble",
    store_name: "Dribbble Design Store",
    billing: {
      first_name: "Eleanor",
      last_name: "Vance",
      company: "Hill House Media",
      address_1: "742 Evergreen Terrace",
      address_2: "Apt 4B",
      city: "Brooklyn",
      state: "NY",
      postcode: "11201",
      country: "US",
      email: "eleanor.vance@hillhouse.design",
      phone: "+1 (555) 234-8901",
    },
    shipping: {
      first_name: "Eleanor",
      last_name: "Vance",
      company: "Hill House Media",
      address_1: "742 Evergreen Terrace",
      address_2: "Apt 4B",
      city: "Brooklyn",
      state: "NY",
      postcode: "11201",
      country: "US",
      email: "eleanor.vance@hillhouse.design",
      phone: "+1 (555) 234-8901",
    },
    line_items: [
      {
        id: 301,
        name: "Artisan Oversized Heavyweight Hoodie",
        product_id: 104,
        variation_id: 1042,
        quantity: 2,
        sku: "AOH-NVY-XL",
        price: 110.0,
        subtotal: "220.00",
        total: "205.00",
        meta_data: [
          { key: "pa_size", value: "Extra Large", display_key: "Size", display_value: "Extra Large" },
          { key: "pa_color", value: "Midnight Navy", display_key: "Color", display_value: "Midnight Navy" },
          { key: "monogram", value: "EV-2026", display_key: "Monogram", display_value: "EV-2026" },
        ],
      },
      {
        id: 302,
        name: "Merino Wool Beanie",
        product_id: 108,
        variation_id: 1081,
        quantity: 1,
        sku: "MWB-BLK-OS",
        price: 46.0,
        subtotal: "46.00",
        total: "46.00",
        meta_data: [
          { key: "pa_color", value: "Charcoal Heather", display_key: "Color", display_value: "Charcoal Heather" },
        ],
      },
    ],
    tax_lines: [
      {
        id: 501,
        rate_code: "NY-STATE-TAX",
        rate_id: 12,
        label: "NY State Sales Tax (8.875%)",
        compound: false,
        tax_total: "21.00",
        shipping_tax_total: "0.00",
      },
    ],
    shipping_lines: [
      {
        id: 601,
        method_title: "Priority Tracked Courier",
        method_id: "flat_rate:priority",
        total: "12.50",
        total_tax: "0.00",
      },
    ],
    coupon_lines: [
      {
        id: 1,
        code: "SUMMER15",
        discount: "15.00",
      },
    ],
    fee_lines: [],
    meta_data: [
      { key: "_stripe_customer_id", value: "cus_P7k982jLm91" },
      { key: "_stripe_fee", value: "8.55" },
      { key: "_shipstation_exported", value: "true" },
      { key: "warehouse_bin_location", value: "BAY-C-14", display_key: "Warehouse Bin Location", display_value: "BAY-C-14" },
      { key: "fraud_score", value: "0.02 (Low Risk)", display_key: "Fraud Score", display_value: "0.02 (Low Risk)" },
      { key: "gift_wrap_requested", value: "Yes (Silk Ribbon)", display_key: "Gift Wrap Requested", display_value: "Yes (Silk Ribbon)" },
      { key: "delivery_instructions", value: "Ring doorbell twice, leave at patio gate if raining", display_key: "Delivery Instructions", display_value: "Ring doorbell twice, leave at patio gate if raining" },
    ],
  },
  {
    id: 1005,
    number: "1005",
    status: "completed",
    currency: "USD",
    currency_symbol: "$",
    date_created: "2026-06-29T09:15:00Z",
    date_created_gmt: "2026-06-29T09:15:00Z",
    discount_total: "0.00",
    shipping_total: "0.00",
    total: "540.00",
    total_tax: "45.00",
    customer_id: 88,
    payment_method: "google_pay",
    payment_method_title: "Google Pay Express Checkout",
    transaction_id: "gpay_txn_8921340192",
    store_id: "store-google",
    store_name: "Google Pay Marketplace",
    billing: {
      first_name: "Marcus",
      last_name: "Sterling",
      address_1: "100 California Street",
      city: "San Francisco",
      state: "CA",
      postcode: "94111",
      country: "US",
      email: "marcus.sterling@apexcapital.io",
      phone: "+1 (415) 890-1234",
    },
    shipping: {
      first_name: "Marcus",
      last_name: "Sterling",
      address_1: "100 California Street",
      city: "San Francisco",
      state: "CA",
      postcode: "94111",
      country: "US",
      email: "marcus.sterling@apexcapital.io",
      phone: "+1 (415) 890-1234",
    },
    line_items: [
      {
        id: 303,
        name: "Mechanical Keycap Artisan Set - Titanium",
        product_id: 202,
        quantity: 1,
        sku: "MKS-TIT-01",
        price: 495.0,
        subtotal: "495.00",
        total: "495.00",
        meta_data: [
          { key: "pa_layout", value: "ANSI-TKL", display_key: "Layout", display_value: "ANSI Tenkeyless" },
          { key: "pa_finish", value: "matte-sandblast", display_key: "Finish", display_value: "Matte Sandblast" },
        ],
      },
    ],
    tax_lines: [
      {
        id: 502,
        rate_code: "CA-SALES-TAX",
        rate_id: 14,
        label: "California State Tax (8.625%)",
        compound: false,
        tax_total: "45.00",
        shipping_tax_total: "0.00",
      },
    ],
    shipping_lines: [
      {
        id: 602,
        method_title: "Free Express Shipping",
        method_id: "free_shipping",
        total: "0.00",
        total_tax: "0.00",
      },
    ],
    coupon_lines: [],
    fee_lines: [],
    meta_data: [
      { key: "_gpay_wallet_token", value: "tok_991823120" },
      { key: "_tracking_number", value: "1Z9999999999999999" },
      { key: "_carrier", value: "UPS Next Day Air" },
      { key: "dispatch_timestamp", value: "2026-06-29T11:00:00Z", display_key: "Dispatch Timestamp", display_value: "2026-06-29 11:00 AM UTC" },
    ],
  },
  {
    id: 1006,
    number: "1006",
    status: "on-hold",
    currency: "USD",
    currency_symbol: "$",
    date_created: "2026-06-28T22:45:00Z",
    date_created_gmt: "2026-06-28T22:45:00Z",
    discount_total: "50.00",
    shipping_total: "24.00",
    total: "890.00",
    total_tax: "66.00",
    customer_id: 115,
    customer_note: "Awaiting bank transfer confirmation.",
    payment_method: "bacs",
    payment_method_title: "Direct Bank Wire Transfer",
    store_id: "store-amazon",
    store_name: "Amazon Storefront Outlet",
    billing: {
      first_name: "Julian",
      last_name: "Decker",
      company: "Decker & Sons Industrial",
      address_1: "45 Bishopsgate",
      city: "London",
      state: "Greater London",
      postcode: "EC2N 4AG",
      country: "GB",
      email: "julian@deckerson.co.uk",
      phone: "+44 20 7946 0912",
    },
    shipping: {
      first_name: "Julian",
      last_name: "Decker",
      company: "Decker & Sons Industrial",
      address_1: "Unit 3, Logistics Way",
      city: "Dartford",
      state: "Kent",
      postcode: "DA1 5FW",
      country: "GB",
      email: "julian@deckerson.co.uk",
      phone: "+44 20 7946 0912",
    },
    line_items: [
      {
        id: 304,
        name: "Ergonomic Carbon Fiber Task Chair",
        product_id: 504,
        quantity: 1,
        sku: "ECF-CHR-BLK",
        price: 850.0,
        subtotal: "850.00",
        total: "800.00",
        meta_data: [
          { key: "pa_cylinder", value: "high-range", display_key: "Cylinder", display_value: "High Range" },
          { key: "pa_casters", value: "rollerblade-pu", display_key: "Casters", display_value: "Rollerblade Polyurethane" },
        ],
      },
    ],
    tax_lines: [
      {
        id: 503,
        rate_code: "GB-VAT",
        rate_id: 20,
        label: "UK Standard VAT (20%)",
        compound: false,
        tax_total: "66.00",
        shipping_tax_total: "4.00",
      },
    ],
    shipping_lines: [
      {
        id: 603,
        method_title: "Freight Pallet Delivery",
        method_id: "freight_standard",
        total: "24.00",
        total_tax: "4.00",
      },
    ],
    coupon_lines: [
      {
        id: 2,
        code: "WELCOME50",
        discount: "50.00",
      },
    ],
    fee_lines: [
      {
        id: 10,
        name: "Pallet Packaging Fee",
        total: "50.00",
        total_tax: "10.00",
      },
    ],
    meta_data: [
      { key: "bacs_reference", value: "WOO-1006-DECKER", display_key: "BACS Reference", display_value: "WOO-1006-DECKER" },
      { key: "payment_status_check", value: "Pending manual ledger reconciliation", display_key: "Payment Verification", display_value: "Pending manual ledger reconciliation" },
    ],
  },
  {
    id: 1007,
    number: "1007",
    status: "completed",
    currency: "USD",
    currency_symbol: "$",
    date_created: "2026-06-28T18:10:00Z",
    date_created_gmt: "2026-06-28T18:10:00Z",
    discount_total: "0.00",
    shipping_total: "9.99",
    total: "149.99",
    total_tax: "12.00",
    customer_id: 204,
    payment_method: "apple_pay",
    payment_method_title: "Apple Pay",
    transaction_id: "ap_9812034981",
    store_id: "store-dribbble",
    store_name: "Dribbble Design Store",
    billing: {
      first_name: "Sophia",
      last_name: "Chen",
      address_1: "220 King St W",
      city: "Toronto",
      state: "ON",
      postcode: "M5H 1K4",
      country: "CA",
      email: "sophia.chen@vector.ca",
      phone: "+1 (416) 555-0199",
    },
    shipping: {
      first_name: "Sophia",
      last_name: "Chen",
      address_1: "220 King St W",
      city: "Toronto",
      state: "ON",
      postcode: "M5H 1K4",
      country: "CA",
      email: "sophia.chen@vector.ca",
      phone: "+1 (416) 555-0199",
    },
    line_items: [
      {
        id: 305,
        name: "Wireless ANC Studio Headphones",
        product_id: 601,
        quantity: 1,
        sku: "WANC-STU-SIL",
        price: 128.0,
        subtotal: "128.00",
        total: "128.00",
        meta_data: [
          { key: "pa_color", value: "silver", display_key: "Colorway", display_value: "Silver Metallic" },
        ],
      },
    ],
    tax_lines: [
      {
        id: 504,
        rate_code: "HST-ON",
        rate_id: 13,
        label: "Ontario HST (13%)",
        compound: false,
        tax_total: "12.00",
        shipping_tax_total: "0.00",
      },
    ],
    shipping_lines: [
      {
        id: 604,
        method_title: "Canada Post Expedited",
        method_id: "cp_expedited",
        total: "9.99",
        total_tax: "0.00",
      },
    ],
    coupon_lines: [],
    fee_lines: [],
    meta_data: [
      { key: "_apple_pay_device_type", value: "iPhone 17 Pro" },
      { key: "_carrier", value: "Canada Post" },
      { key: "_tracking_number", value: "CP982340912CA" },
      { key: "custom_gift_message", value: "Happy Birthday Sophia!", display_key: "Gift Message", display_value: "Happy Birthday Sophia!" },
    ],
  },
  {
    id: 1008,
    number: "1008",
    status: "cancelled",
    currency: "USD",
    currency_symbol: "$",
    date_created: "2026-06-27T14:20:00Z",
    date_created_gmt: "2026-06-27T14:20:00Z",
    discount_total: "0.00",
    shipping_total: "15.00",
    total: "320.00",
    total_tax: "24.00",
    customer_id: 67,
    customer_note: "Customer cancelled prior to dispatch.",
    payment_method: "stripe",
    payment_method_title: "Credit Card via Stripe",
    store_id: "store-google",
    store_name: "Google Pay Marketplace",
    billing: {
      first_name: "Liam",
      last_name: "O'Connor",
      address_1: "14 Grafton Street",
      city: "Dublin",
      state: "Leinster",
      postcode: "D02 AY89",
      country: "IE",
      email: "liam.oconnor@dublintech.ie",
      phone: "+353 1 496 0123",
    },
    shipping: {
      first_name: "Liam",
      last_name: "O'Connor",
      address_1: "14 Grafton Street",
      city: "Dublin",
      state: "Leinster",
      postcode: "D02 AY89",
      country: "IE",
      email: "liam.oconnor@dublintech.ie",
      phone: "+353 1 496 0123",
    },
    line_items: [
      {
        id: 306,
        name: "Mechanical Split Keyboard - Walnut Shell",
        product_id: 708,
        quantity: 1,
        sku: "MSK-WLN-01",
        price: 281.0,
        subtotal: "281.00",
        total: "281.00",
        meta_data: [
          { key: "pa_switches", value: "tactile-boba-u4t", display_key: "Switches", display_value: "Gazzew Boba U4T" },
        ],
      },
    ],
    tax_lines: [
      {
        id: 505,
        rate_code: "IE-VAT",
        rate_id: 23,
        label: "Irish Standard VAT (23%)",
        compound: false,
        tax_total: "24.00",
        shipping_tax_total: "0.00",
      },
    ],
    shipping_lines: [
      {
        id: 605,
        method_title: "DHL Express International",
        method_id: "dhl_intl",
        total: "15.00",
        total_tax: "0.00",
      },
    ],
    coupon_lines: [],
    fee_lines: [],
    meta_data: [
      { key: "cancellation_reason", value: "Customer order duplicate", display_key: "Cancellation Reason", display_value: "Customer order duplicate" },
      { key: "refund_status", value: "Full refund reversed to card ending in 4242", display_key: "Refund Status", display_value: "Full refund reversed to card ending in 4242" },
    ],
  },
  {
    id: 1009,
    number: "1009",
    status: "refunded",
    currency: "USD",
    currency_symbol: "$",
    date_created: "2026-06-26T11:00:00Z",
    date_created_gmt: "2026-06-26T11:00:00Z",
    discount_total: "10.00",
    shipping_total: "8.00",
    total: "98.00",
    total_tax: "7.50",
    customer_id: 99,
    payment_method: "paypal",
    payment_method_title: "PayPal Express",
    transaction_id: "pp_capture_49102830",
    store_id: "store-dribbble",
    store_name: "Dribbble Design Store",
    billing: {
      first_name: "Chloe",
      last_name: "Dupont",
      address_1: "18 Rue de Rivoli",
      city: "Paris",
      state: "Île-de-France",
      postcode: "75004",
      country: "FR",
      email: "chloe.dupont@atelier.fr",
      phone: "+33 1 42 68 55 00",
    },
    shipping: {
      first_name: "Chloe",
      last_name: "Dupont",
      address_1: "18 Rue de Rivoli",
      city: "Paris",
      state: "Île-de-France",
      postcode: "75004",
      country: "FR",
      email: "chloe.dupont@atelier.fr",
      phone: "+33 1 42 68 55 00",
    },
    line_items: [
      {
        id: 307,
        name: "Ceramic Minimalist Desk Planter",
        product_id: 812,
        quantity: 2,
        sku: "CMDP-WHT",
        price: 45.0,
        subtotal: "90.00",
        total: "80.00",
        meta_data: [
          { key: "pa_finish", value: "glazed-matte", display_key: "Finish", display_value: "Glazed Eggshell" },
        ],
      },
    ],
    tax_lines: [
      {
        id: 506,
        rate_code: "FR-TVA",
        rate_id: 20,
        label: "French TVA (20%)",
        compound: false,
        tax_total: "7.50",
        shipping_tax_total: "0.00",
      },
    ],
    shipping_lines: [
      {
        id: 606,
        method_title: "Colissimo Standard",
        method_id: "colissimo",
        total: "8.00",
        total_tax: "0.00",
      },
    ],
    coupon_lines: [
      {
        id: 3,
        code: "CERAMIC10",
        discount: "10.00",
      },
    ],
    fee_lines: [],
    meta_data: [
      { key: "return_rma", value: "RMA-2026-908", display_key: "RMA Return Number", display_value: "RMA-2026-908" },
      { key: "inspection_status", value: "Restocked in good order", display_key: "Inspection Status", display_value: "Restocked in good order" },
    ],
  },
];
